- .github/workflows/apply-formatting.yml
- .github/workflows/check-formatting.yml
This PR adds two GitHub workflows. `check-formatting.yml` adds a CI item for checking that code is formatted. `apply-formatting.yml` adds a GitHub Action that monitors for comments that start with "@par-hermes format", and applies formatting for that code. You can use "@par-hermes format --amend" to squash the formatting change into the prior commit.
- [~] New features are documented. (TODO: Will document once it's working)
> Add workflows for formatting C++ code

- src/interface/Metadata.cpp
- src/interface/Metadata.hpp
- tst/unit/test_metadata.cpp
Fixes #84 as identified by @jdolence, and then also fixes a related issues in the comparison operator. I added some new tests, too.
Also fixes up cpplint issues that were pre-existing.
> Fix Metadata::IsSet, operator==, and operator!=

- .gitlab-ci.yml
When debugging failed CI it can often be helpful to have more than CLI output. In this merge request, I enable the saving of "artifacts," files generated during a test. This both shows how it can be done and generalized and provides two files which might be useful to look at if your code fails to build.
> CI Saves Some Build Logs

- CMakeLists.txt
- src/CMakeLists.txt
This change gets the code building with IBM XL 16.1.1.7. Only required a couple small CMake changes.
The tests currently fail due to an issue with IBM XL when used with Catch2. When the fix to Catch2 is merged, I will update our Catch2 version: https://github.com/catchorg/Catch2/pull/1907
> Get code building with IBM XL on Power 9

- docs/parthenon_arrays.md
- src/kokkos_abstraction.hpp
- src/mesh/mesh.hpp
- src/mesh/meshblock.cpp
- src/outputs/parthenon_hdf5.cpp
- src/parthenon_arrays.hpp
- tst/unit/kokkos_abstraction.cpp
- tst/unit/test_container_iterator.cpp
- tst/unit/test_pararrays.cpp
- tst/unit/test_unit_face_variables.cpp
Addressed two items
- Cleanup of the `DevSpace` and `HostSpace` types that incorrectly were used for both execution and memory spaces (lead to problems with the wrappers when enabling UVM). Now there are `DevExecSpace`, `DevMemSpace`, and `HostMemSpace` to distinguish between those.
- Add a `GetHostMirrorAndCopy` function to the `ParArrays`s which does what it name stands for. This will be useful, e.g., during the simulation setup in the process of Kokkosizing the remainder of the codebase.
> Fix space typedefs. Add GetHostMirrorAndCopy

- cmake/CheckCopyright.cmake
- cmake/Format.cmake
Don't format or check copyright in files starting with `.`
> fix CMake GLOB expressions to not match files starting with .

- CMakeLists.txt
Currently the 'make test' target doesn't ensure that binaries are not stale before they are run.  This is a well known issue with Cmake/Ctest.  To ensure that my test is not running with out-of-date binaries, I added a custom target "checkit" that will build the unit tests before they are run.   Normally I would use the target 'check', but that was already taken by Kokkos.
If other tests are added with different binaries, those binaries should be added to the DEPENDS line
> Ensure that binaries are built before testing

- src/parthenon_arrays.hpp
- tst/unit/test_pararrays.cpp
In issue #135 @pgrete found a bug in the implementation of slicing for `ParArrayND`. In particular, the slices into the given dimensions were wrong. Some `Kokkos::ALL()`s should have been `SLC0`s. 
I fixed the bug and added tests for those two slice use cases to ensure that the behavior is caught if it breaks again.
> fix pararray slice bug and add tests for previously broken behaviour

- src/mesh/mesh.hpp
- src/mesh/meshblock.cpp
I have created a new constructor for Parthenon::Meshblock(int n_side, int dim) so that we can initialize containers with ghost cells within them.  This just populates the ncells[123 and ncc[123] components of the mesh block.
> added interface to create a dummy meshblock for performance testing.

- tst/regression/test_suites/calculate_pi/parthinput.regression
Somehow the updated parthinput.regression for the calculate_pi regression test didn't make it into master, leading to test failures.
I'm going to merge this in as soon as the tests pass.
> fix mysteriously outdated regression test input

- docs/README.md
- docs/nested_par_for.md
- src/CMakeLists.txt
- src/kokkos_abstraction.hpp
- src/mesh/mesh.hpp
- tst/unit/kokkos_abstraction.cpp
Adding nested parallel for loop abstractions `par_outer_loop` and `par_inner_loop` to abstract team level parallelisms and Kokkos scratch memory.
Adds the nested parallel for wrappers `par_outer_loop` and `par_inner_loop` that abstract elements of the Kokkos hierarchical parallelism for more convenient use on 3D and 4D grids. These wrappers allow management of cache memory which is necessary for efficient reconstruction kernels.
> Nested Parallel For

- src/outputs/parthenon_hdf5.cpp
Trying to fix the issue @pgrete found with looking at multicomponent variables in paraview.
Should address #160.
> potential fix for multicomponent fields in hdf5 dumps with paraview

- .gitlab-ci.yml
- src/driver/driver.cpp
- src/driver/multistage.cpp
- src/kokkos_abstraction.hpp
- src/mesh/mesh.hpp
- src/outputs/outputs.cpp
- src/parameter_input.cpp
- src/pgen/default_pgen.cpp
As the title suggest, multiple small fixes I stumbled across when integrating with AthenaPK:
- Enforce cpplint (stage is not allowed to fail any more during CI, but also run last so that regression tests will always executed first)
- reintroduce UserWorkAfterLoop (Athena++ feature that we removed from the ParthenonManager/driver infrastructure during transition -- very helpful for regression/convergence tests)
- add VL2 integrator beta (also reintroduced from original Athena++ code)
- fix cmd line parsing to override input parameter options (the addition of prefixes, such as `parthenon/time` broke the parsing based on the first occurrence of `/`. Now works for both blocks with and without prefixes).
> Enforce cpplint, reintroduce UserWorkAfterLoop, add VL2 integrator, fix cmd line parsing

- src/utils/error_checking.hpp
`fprintf` is not available on devices. Thus, we need to use `printf` (and cannot print to stderr).
> Fix printf in kernels

- CMakeLists.txt
- docs/README.md
- src/interface/params.hpp
- src/parameter_input.cpp
- src/utils/error_checking.hpp
- tst/unit/CMakeLists.txt
- tst/unit/test_error_checking.cpp
As discussed in issue #171 I replace `std::string` and `exit` with `char[]` and `Kokkos::abort`. This functionality should actually work on GPUs and should be performance portable thanks to the `Kokkos::abort` call.
Some things to note:
- I actually use `const char * const`, not `char[]`. I copied this from the implementation of `Kokkos::abort`. I suppose the extra const is more clear but `const char[]` would almost certainly be fine.
- The places in the code calling `PARTHENON_ABORT` and `PARTHENON_REQUIRE` used C++ strings. I had to modify them slightly to pass in a C-style string.
- I added a unit test that tests the error-checking. Kokkos abort, however, obviously kills your program. So the test fails. Therefore, I guard the test in an ifdef. To activate it, configure with `cmake …
> kokkosify error checking macros

- example/advection/advection_package.cpp
- example/advection/redefine_parthenon_defaults.cpp
Emergency fix as recent merge #172 broke master (#165 introduced new calls to `PARTHENON_FAIL` which were not part of the base of #172 when merging.
> Fix string usage in fail message

- .gitlab-ci.yml
- CMakeLists.txt
- docs/building.md
- src/CMakeLists.txt
Exposed Parthenon build parameters that host codes might want to modify.  These were also prefixed by a PARTHENON_ .  These include:
1. PARTHENON_DISABLE_MPI
1. PARTHENON_DISABLE_HDF5
1. PARTHENON_DISABLE_OPENMP
1. PARTHENON_NGHOST
1. PARTHENON_SINGLE_PRECISION
> Ensure that Parthenon build parameters set by host codes are evidently parthenon

- example/advection/advection_driver.cpp
- example/advection/advection_driver.hpp
- src/interface/variable.hpp
- src/task_list/tasks.hpp
This is a trivial change that restores the label field host side for the CellVariable class.  This should avoid the need to make deep copies from the device.
May help address concerns raised in #189.
> Use host side labels

- example/advection/advection_package.cpp
- src/config.hpp.in
Replaced local definition of PI with M_PI.
> Removed PI and TWO_PI from defs.hpp.in

- docs/tasks.md
- example/advection/advection_driver.cpp
- src/interface/container.cpp
- src/interface/container.hpp
- src/parthenon/prelude.hpp
- src/tasks/task_list.hpp
This PR adds an overload of the AddTask function that enables app developers to add non-static class member functions to task lists.  The interface is necessarily slightly different because non-static member functions need to be invoked by an object of the class, which in turn needs to be captured by the lambda we use to represent tasks.
Addresses #231
> Allow non-static class member functions to be tasks

- cmake/CodeCov.cmake
- cmake/TestSetup.cmake
- tst/regression/CMakeLists.txt
Fixes an incorrect cmake variable that uses the wrong path when parthenon is included as a submodule. https://github.com/lanl/parthenon/issues/233
> Correct CMAKE variable, make local to project

- docs/parthenon_arrays.md
A while ago, @pgrete found some unintuitive, but correct, behaviour for `ParArrayND` when it is typecast. I documented this in issue #143. I don't think the code needs to change, but @AndrewGaspar suggested documenting the behavior in the docs and pointing to the issue. I agree. This MR implements that documentation.
> Document ParArrayND Typecasting, Closes #143
